blank_issues_enabled: true
contact_links:
  - name: Wifibox Support
    url: https://github.com/pgj/freebsd-wifibox/discussions
    about: Please ask and answer questions, share project related information here.
